### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by rffontenelle**

### CODE REVIEW

**Comment by rascarlo** [comment]
@rffontenelle Hi, could you please look at the new strings file resources and see if you can help? Thanks

**Comment by rffontenelle** [comment]
@rascarlo Done.

**Comment by rascarlo** [comment]
Thank you! Should I link your github account for the credit?

**Comment by rffontenelle** [comment]
@rascarlo sure, go ahead

**Comment by rascarlo** [comment]
done: https://github.com/rascarlo/AURdroid/commit/315803b23d13150bdbce9e0d50b9dc7b297b2074

**Pull request merged**
